apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalog
    tier: backend
  name: catalog
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
      tier: backend
  template:
    metadata:
      labels:
        app: catalog
        tier: backend
    spec:
      containers:
      - env:
        - name: CSE_REGISTRY_ADDR
          value: http://servicecenter:30100
        image: eazytraining/catalog:1.0.0
        name: catalog
