apiVersion: v1
kind: Service
metadata:
  name: servicecenter
  namespace: microservices
spec:
  ports:
  - name: servicecenterport
    port: 30100
    targetPort: 30100
  selector:
    app: servicecenter
