apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicecenter
  name: servicecenter
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicecenter
  template:
    metadata:
      labels:
        app: servicecenter
    spec:
      containers:
      - image: servicecomb/service-center:1.0.0
        name: servicecenter
